  CREATE TABLE PERSON_WEEK12
   (	ID NUMBER NOT NULL, 
      USERNAME VARCHAR2(35)NOT NULL,
      FIRSTNAME VARCHAR2(35) NOT NULL, 
      LASTNAME VARCHAR2(35) NOT NULL	
   );
  CREATE TABLE ROLEMAPPING_WEEK12
   (	
       ROLEID NUMBER NOT NULL, 
	   USERID NUMBER NOT NULL
   );
   CREATE TABLE ROLETABLE_WEEK12
   (	ROLEID NUMBER , 
	ROLENAME VARCHAR2(40)
   );  

   
   ALTER TABLE PERSON_WEEK12 ADD PRIMARY KEY (ID);
   
    ALTER TABLE ROLEMAPPING_WEEK12 ADD PRIMARY KEY(ROLEID,USERID);
   
   ALTER TABLE ROLETABLE_WEEK12 ADD PRIMARY KEY (ROLEID);
   
   ALTER TABLE ROLEMAPPING_WEEK12
 ADD CONSTRAINT fk_key_role
  FOREIGN KEY (USERID)
  REFERENCES PERSON_WEEK12(ID);
  
  ALTER TABLE ROLEMAPPING_WEEK12
  ADD CONSTRAINT fk_key_map
  FOREIGN KEY (ROLEID)
  REFERENCES ROLETABLE_WEEK12(ROLEID);
 