  CREATE TABLE PERSON
   (	ID NUMBER NOT NULL, 
	FIRSTNAME VARCHAR2(35) NOT NULL, 
	LASTNAME VARCHAR2(35) NOT NULL	
   )
  CREATE TABLE ROLEMAPPING
   (	
       ROLEID NUMBER NOT NULL, 
	   USERID NUMBER NOT NULL
   )
   CREATE TABLE ROLETABLE
   (	ROLEID NUMBER , 
	ROLENAME VARCHAR2(40)
   )  

   
   ALTER TABLE PERSON ADD PRIMARY KEY (ID);
   
    ALTER TABLE ROLEMAPPING ADD PRIMARY KEY(ROLEID,USERID);
   
   ALTER TABLE ROLETABLE ADD PRIMARY KEY (ROLEID);
   
   ALTER TABLE ROLEMAPPING
 ADD CONSTRAINT fk_key_rowmap
  FOREIGN KEY (USERID)
  REFERENCES PERSON(ID);
  
  ALTER TABLE ROLEMAPPING
  ADD CONSTRAINT fk_key_rolemap
  FOREIGN KEY (ROLEID)
  REFERENCES ROLETABLE(ROLEID);
 